site_name: Кооперативная Экономика

theme:
  name: material
  # custom_dir: overrides
  palette:
    primary: indigo

  logo: assets/logo-white.png

  language: ru
  features:
    - navigation.path
    - navigation.tabs
    # - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.expand
    - toc.follow
    - toc.integrate
    - search.share
repo_url: https://github.com/dicoop

plugins:
  - search
  - awesome-pages
  # - social:
  #   cards_layout: default

  # - literate-nav:
  # nav_file: SUMMARY.md

extra:
  generator: false

# copyright: Copyright &copy; 2023

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Доктрина:
      - index.md
      - Цифровые валюты Центральных Банков: digital-currencies.md
      - Экономическая доктрина кооперативной экономики: doctrine.md
      - Моральная (этичная) экономика: moral-economic.md
      - Цифровизация: moral-economic.md
      - Национальная Идея: moral-economic.md
  - Цифровой Кооператив:
      - dicoop/index.md
  - Вопрос - ответ:
      - instructions/index.md
    # - Создать аккаунт: registration.md
    # - Вступить в пайщики: joincoop.md
  - Разработчикам: https://dev.dicoop.space/html/index.html
  - Маркетплейс: https://change.dicoop.space
  - Обозреватель: https://explorer.dicoop.space
