site_name: Кооперативная Экономика

theme:
  name: material
  features:
    - content.code.copy
    
  # custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: teal

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: teal
  
  logo: assets/logo-white.png

  language: ru
  features:
    - navigation.path
    - navigation.tabs
    # - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.expand
    # - toc.follow
    - toc.integrate
    - search.share
    - navigation.top
    - navigation.footer
    
repo_url: https://github.com/copenomics

plugins:
  - search
  - awesome-pages
  # - table-reader
  - blog
  # - social:https://squidfunk.github.io/mkdocs-material/
  #   cards_layout: default

  # - literate-nav:
  # nav_file: SUMMARY.md

extra:
  generator: false
  # social:
  #   - icon: fontawesome/brands/telegram
  #     link: https://twitter.com/your-profile

copyright: ПК «ВОСХОД» &copy; 2024

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    # - pymdownx.superfences:
    #   custom_fences:
    #     - name: mermaid
    #       class: mermaid
    #       format: !!python/name:pymdownx.superfences.fence_code_format

      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:pymdownx.superfences.fence_code_format


  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  # - Миссия: index.md  
  - Доктрина: index.md
  # - Методология: metodology.md
  - Документация: documentation.md
  - Протоколы: 
      - Эмиссии: protocols/emission.md
      # - protocols.md
  # - Словарь: vocabulary.md
  # - FAQ: faq.md  
  - Председателям: info.md  
  - Вкладчикам: invest.md
  - Подключение: connect.md
  - Блог: 
      - blog/index.md
  - Форум: https://forum.copenomics.world
  - Контакты: contacts.md
  
 