site_name: Кооперативная Экономика

theme:
  name: material
  # custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: teal

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: teal
  
  logo: assets/logo-white.png

  language: ru
  features:
    - navigation.path
    - navigation.tabs
    # - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.expand
    # - toc.follow
    - toc.integrate
    - search.share
    - navigation.top
    - navigation.footer
    
repo_url: https://github.com/intellect-run

plugins:
  - search
  - awesome-pages
  # - social:
  #   cards_layout: default

  # - literate-nav:
  # nav_file: SUMMARY.md

extra:
  generator: false

copyright: АНО «Кооперативная Экономика» &copy; 2023

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Доктрина: index.md
  - Словарь: vocabulary.md
  - Платформа: dicoop/index.md
  - Документация: dev/index.md
  - Вопрос - ответ: instructions/index.md  
  - Подключиться: joincoop.md
  # - Витрина: joincoop.md
  # - Документация: https://dev.dicoop.space/html/index.html
  
 